# Используем язык java.
language: java
# Используем режим обычного пользователя для сборки проекта.
sudo: false
jdk: oraclejdk9
services:
  - postgresql
before_script:
  - psql -c 'create database tracker;' -U postgres
# После выполнения сборки запустить скрипт, который будет собирать статистику по JaCoCo
# используем сторонний сервис https://codecov.io/
after_success:
  - bash <(curl -s https://codecov.io/bash)

# Отправлять уведомление на почту если сборка упала
notifications:
  email:
    recipients:
      - fast2016@mail.ru
    on_success: never # default: change
    on_failure: always # default: always